
const Actions = {
    AUTHENTICATED : "AUTHENTICATED",
    MENUACTION : 'MENUACTION', 
    MENUDESKTOPACTION:"MENUDESKTOPACTION",
    OVERLAYACTION : "OVERLAYACTION",
    USERCREATED : "USERCREATED",
    LOGINDETAIL : "LOGINDETAIL",
    USERDETAIL : "USERDETAIL",
    SETUSERFULLDATA : "SETUSERFULLDATA",
    SETINVESTMENTDATA : "SETINVESTMENTDATA"
}
export default Actions


